// Package printer renders the AST to TypeScript source text.
//
// Parentheses are inserted wherever operator precedence requires them, so
// callers never need to reason about precedence when building trees.
package printer

import "strings"

// QuoteStyle selects the quote character for emitted string literals.
type QuoteStyle uint8

const (
	SingleQuote QuoteStyle = iota
	DoubleQuote
	BacktickQuote
)

// MemberSeparator selects the punctuation between object type members.
type MemberSeparator uint8

const (
	SemicolonSeparator MemberSeparator = iota
	CommaSeparator
	NewlineSeparator // no punctuation; members separated by line breaks only
)

// Options controls emission. The zero value is not the default; use
// [Default] or pass [Option] values to [New].
type Options struct {
	// Indent is one level of indentation. Use "\t" for tabs.
	Indent string

	// Quote is the quote character for string literals.
	Quote QuoteStyle

	// Semicolons emits statement terminators.
	Semicolons bool

	// MemberSep is the separator between interface and object type members.
	MemberSep MemberSeparator

	// TrailingComma emits a trailing comma in multi-line lists.
	TrailingComma bool

	// MaxLineWidth is the column at which unions, parameter lists, and object
	// literals break across lines. Zero disables wrapping entirely.
	MaxLineWidth int

	// EmitDocs emits JSDoc comments attached to declarations and members.
	EmitDocs bool

	// Banner is emitted at the top of a SourceFile, before its own Leading
	// comments. Each entry becomes one line; the caller supplies any comment
	// syntax. This is where a "generated, do not edit" header belongs.
	Banner []string

	// FinalNewline terminates the output with a line break.
	FinalNewline bool
}

// Default returns the recommended configuration: two-space indent, single
// quotes, semicolons, docs on, wrapping at 100 columns.
func Default() Options {
	return Options{
		Indent:        "  ",
		Quote:         SingleQuote,
		Semicolons:    true,
		MemberSep:     SemicolonSeparator,
		TrailingComma: true,
		MaxLineWidth:  100,
		EmitDocs:      true,
		FinalNewline:  true,
	}
}

// Option mutates Options. Options compose.
type Option func(*Options)

// WithIndent sets one level of indentation.
func WithIndent(s string) Option { return func(o *Options) { o.Indent = s } }

// WithTabs indents with tabs.
func WithTabs() Option { return func(o *Options) { o.Indent = "\t" } }

// WithQuote sets the string literal quote style.
func WithQuote(q QuoteStyle) Option { return func(o *Options) { o.Quote = q } }

// WithSemicolons enables or disables statement terminators.
func WithSemicolons(b bool) Option { return func(o *Options) { o.Semicolons = b } }

// WithMemberSeparator sets the interface member separator.
func WithMemberSeparator(s MemberSeparator) Option {
	return func(o *Options) { o.MemberSep = s }
}

// WithMaxLineWidth sets the wrapping column; zero disables wrapping.
func WithMaxLineWidth(n int) Option { return func(o *Options) { o.MaxLineWidth = n } }

// WithDocs enables or disables JSDoc emission.
func WithDocs(b bool) Option { return func(o *Options) { o.EmitDocs = b } }

// WithBanner sets the file header lines, which are emitted verbatim.
func WithBanner(lines ...string) Option { return func(o *Options) { o.Banner = lines } }

// WithTrailingComma enables or disables trailing commas in wrapped lists.
func WithTrailingComma(b bool) Option { return func(o *Options) { o.TrailingComma = b } }

// GeneratedBanner returns the conventional header for generated files.
func GeneratedBanner(by string) Option {
	return WithBanner(
		"// Code generated by "+by+". DO NOT EDIT.",
		"// @generated",
		"/* eslint-disable */",
	)
}

func (o Options) quoteChar() byte {
	switch o.Quote {
	case DoubleQuote:
		return '"'
	case BacktickQuote:
		return '`'
	default:
		return '\''
	}
}

func (o Options) memberSepText() string {
	switch o.MemberSep {
	case CommaSeparator:
		return ","
	case NewlineSeparator:
		return ""
	default:
		return ";"
	}
}

func (o Options) semi() string {
	if o.Semicolons {
		return ";"
	}
	return ""
}

func (o Options) indentString(n int) string {
	if n <= 0 {
		return ""
	}
	return strings.Repeat(o.Indent, n)
}
